[auth]
usernames = ["admin", "teacher1", "teacher2"]
names = ["Admin User", "Teacher 1", "Teacher 2"]
passwords = ["zadium", "kinane", "niema"]

[supabase]
url = "https://wgiushgiavongvbzkuvh.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnaXVzaGdpYXZvbmd2YnprdXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzODkyMzYsImV4cCI6MjA3NDk2NTIzNn0.h2UtclD7Bqq5oyYKxq5k3c98827Rzd-bcmX024OTe74"

[postgres]
host = "db.wgiushgiavongvbzkuvh.supabase.co"
database = "postgres"
user = "Perf"
password = "zadium@2025"
port = 5432